package communityDB;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hns.bean.Community;
import org.hns.bean.User;

// Generated 2012-11-25 23:47:23 by Hibernate Tools 3.4.0.CR1

/**
 * Topic generated by hbm2java
 */
public class CommunityItem implements java.io.Serializable {
	
	private Integer topicId;
	private Integer userId;
	private String tpContent;
	private String tpPic;
	private String tpTitle;
	private Integer communityId;
	private Date createTime;
	private Topicinfo topicinfo;
	private Set itemreplies = new HashSet(0);

	public CommunityItem() {
	}

	public CommunityItem(Integer communityId, Integer userId, String tpTitle) {
		this.communityId = communityId;
		this.userId = userId;
		this.tpTitle = tpTitle;
	}

	public CommunityItem(Integer communityId, Integer userId,
			String tpContent, String tpPic, String tpTitle, Set itemreplies) {
		this.communityId = communityId;
		this.userId = userId;
		this.tpContent = tpContent;
		this.tpPic = tpPic;
		this.tpTitle = tpTitle;
		this.itemreplies = itemreplies;
	}

	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}


	public String getTpContent() {
		return this.tpContent;
	}

	public void setTpContent(String tpContent) {
		this.tpContent = tpContent;
	}

	public String getTpPic() {
		return this.tpPic;
	}

	public void setTpPic(String tpPic) {
		this.tpPic = tpPic;
	}

	public String getTpTitle() {
		return this.tpTitle;
	}

	public void setTpTitle(String tpTitle) {
		this.tpTitle = tpTitle;
	}
	
	public Set getItemreplies() {
		return this.itemreplies;
	}

	public void setItemreplies(Set itemreplies) {
		this.itemreplies = itemreplies;
	}
	
	public Integer getCommunityId(){
		return this.communityId;
	}
	
	public void setCommunityId(Integer communityId){
		this.communityId = communityId;
	}
	
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	

	public Topicinfo getTopicinfo() {
		return topicinfo;
	}

	public void setTopicinfo(Topicinfo topicinfo) {
		this.topicinfo = topicinfo;
	}
}
