package communityDB;

// Generated 2012-12-17 1:26:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import org.hns.bean.User;

/**
 * Itemreply generated by hbm2java
 */
public class Itemreply implements java.io.Serializable {

	private Integer replyId;
	private Integer communityId;
	private Integer topicId;
	private Integer userId;
	private String rpContent;
	private String rpPic;
	private String username;
	private Integer targetId;
	private Date createTime;
	private User user;

	public Itemreply() {
	}

	public Itemreply(Integer communityId, Integer topicId,
			 Integer userId, String rpContent, String username) {
		this.communityId = communityId;
		this.topicId = topicId;
		this.userId = userId;
		this.rpContent = rpContent;
		this.username = username;
	}

	public Itemreply(Integer communityId, Integer topicId,
			 Integer userId, String rpContent, String rpPic, String username,
			Integer targetId, Date createTime) {
		this.communityId = communityId;
		this.topicId = topicId;
		this.userId = userId;
		this.rpContent = rpContent;
		this.rpPic = rpPic;
		this.username = username;
		this.targetId = targetId;
		this.createTime = createTime;
	}

	public Integer getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}


	public Integer getCommunityId() {
		return communityId;
	}

	public void setCommunityId(Integer communityId) {
		this.communityId = communityId;
	}

	public Integer getTopicId() {
		return topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getRpContent() {
		return this.rpContent;
	}

	public void setRpContent(String rpContent) {
		this.rpContent = rpContent;
	}

	public String getRpPic() {
		return this.rpPic;
	}

	public void setRpPic(String rpPic) {
		this.rpPic = rpPic;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Integer targetId) {
		this.targetId = targetId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
