package communityDB;

// Generated 2012-12-27 22:23:41 by Hibernate Tools 3.4.0.CR1

/**
 * Notice generated by hbm2java
 * 
 * @author bjrara
 */
public class Notice implements java.io.Serializable {

	private Integer noticeId;
	private Integer toUserId;
	private Integer topicId;
	private Integer replyId;
	private String topicUrl;
	private String fromUsername;
	private Integer noticed;
	/*
	 * 0 noticed 1 not noticed
	 */
	private String tpTitle;

	public Notice() {
	}

	public Notice(Integer toUserId, Integer topicId, String topicUrl,
			String fromUsername, Integer noticed, String tpTitle) {
		this.toUserId = toUserId;
		this.topicId = topicId;
		this.topicUrl = topicUrl;
		this.fromUsername = fromUsername;
		this.noticed = noticed;
		this.tpTitle = tpTitle;
	}

	public Notice(Integer userId, Integer topicId, Integer replyId,
			String topicUrl, String fromUsername, Integer noticed,
			String tpTitle) {
		this.toUserId = userId;
		this.topicId = topicId;
		this.replyId = replyId;
		this.topicUrl = topicUrl;
		this.fromUsername = fromUsername;
		this.noticed = noticed;
		this.tpTitle = tpTitle;
	}

	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public Integer getToUserId() {
		return toUserId;
	}

	public void setToUserId(Integer toUserId) {
		this.toUserId = toUserId;
	}

	public Integer getTopicId() {
		return topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	public Integer getReplyId() {
		return replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}

	public String getTopicUrl() {
		return this.topicUrl;
	}

	public void setTopicUrl(String topicUrl) {
		this.topicUrl = topicUrl;
	}

	public String getFromUsername() {
		return this.fromUsername;
	}

	public void setFromUsername(String fromUsername) {
		this.fromUsername = fromUsername;
	}

	public Integer getNoticed() {
		return this.noticed;
	}

	public void setNoticed(Integer noticed) {
		this.noticed = noticed;
	}

	public String getTpTitle() {
		return tpTitle;
	}

	public void setTpTitle(String tpTitle) {
		this.tpTitle = tpTitle;
	}

}
