package communityDB;

// Generated 2012-12-25 19:42:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Topicinfo generated by hbm2java
 */
public class Topicinfo implements java.io.Serializable {

	private Integer topicId;
	private Date updateTime;
	private Integer replyNum;
	private String replier;
	private String author;
	private Integer hitNum;

	public Topicinfo() {
	}

	public Topicinfo(Integer topicId, Date updateTime,
			Integer replyNum, String author, Integer hitNum) {
		this.topicId = topicId;
		this.updateTime = updateTime;
		this.replyNum = replyNum;
		this.author = author;
		this.hitNum = hitNum;
	}

	public Topicinfo(Integer topicId, Date updateTime,
			Integer replyNum, String replier, String author, Integer hitNum) {
		this.topicId = topicId;
		this.updateTime = updateTime;
		this.replyNum = replyNum;
		this.replier = replier;
		this.author = author;
		this.hitNum = hitNum;
	}

	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Integer getReplyNum() {
		return this.replyNum;
	}

	public void setReplyNum(Integer replyNum) {
		this.replyNum = replyNum;
	}

	public String getReplier() {
		return this.replier;
	}

	public void setReplier(String replier) {
		this.replier = replier;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Integer getHitNum() {
		return this.hitNum;
	}

	public void setHitNum(Integer hitNum) {
		this.hitNum = hitNum;
	}

}
