package communityDB;

// Generated 2012-11-24 18:02:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer userId;
	private String weiboId;
	private String accessToken;
	private String refreshToken;
	private String expireTime;
	private Set<Topic> topics = new HashSet<Topic>(0);

	public Userinfo() {
	}

	public Userinfo(String weiboId, String accessToken) {
		this.weiboId = weiboId;
		this.accessToken = accessToken;
	}

	public Userinfo(String weiboId, String accessToken, String refreshToken,
			String expireTime, Set<Topic> topics) {
		this.weiboId = weiboId;
		this.accessToken = accessToken;
		this.refreshToken = refreshToken;
		this.expireTime = expireTime;
		this.topics = topics;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getWeiboId() {
		return this.weiboId;
	}

	public void setWeiboId(String weiboId) {
		this.weiboId = weiboId;
	}

	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

	public String getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(String expireTime) {
		this.expireTime = expireTime;
	}

	public Set<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

}
