$(document).ready(function(){
$(".flour_right").mouseover(function(){
$(".replyandtrans").show();
});
});
$(document).ready(function(){
$(".flour_right").mouseout(function(){
$(".replyandtrans").hide();
});
});
$(document).ready(function(){
$(".flour_right1").mouseover(function(){
$(".replyandtrans1").show();
});
});
$(document).ready(function(){
$(".flour_right1").mouseout(function(){
$(".replyandtrans1").hide();
});
});
$(document).ready(function(){
$(".flour_right2").mouseover(function(){
$(".replyandtrans2").show();
});
});
$(document).ready(function(){
$(".flour_right2").mouseout(function(){
$(".replyandtrans2").hide();
});
});
$(document).ready(function(){
$(".flour_right3").mouseover(function(){
$(".replyandtrans3").show();
});
});
$(document).ready(function(){
$(".flour_right3").mouseout(function(){
$(".replyandtrans3").hide();
});
});
$(document).ready(function(){
$(".flour_right4").mouseover(function(){
$(".replyandtrans4").show();
});
});
$(document).ready(function(){
$(".flour_right4").mouseout(function(){
$(".replyandtrans4").hide();
});
});
$(document).ready(function(){
$(".flour_right5").mouseover(function(){
$(".replyandtrans5").show();
});
});
$(document).ready(function(){
$(".flour_right5").mouseout(function(){
$(".replyandtrans5").hide();
});
});
$(document).ready(function(){
$(".flour_right6").mouseover(function(){
$(".replyandtrans6").show();
});
});
$(document).ready(function(){
$(".flour_right6").mouseout(function(){
$(".replyandtrans6").hide();
});
});
$(document).ready(function(){
$(".flour_right7").mouseover(function(){
$(".replyandtrans7").show();
});
});
$(document).ready(function(){
$(".flour_right7").mouseout(function(){
$(".replyandtrans7").hide();
});
});
// JavaScript Document